# refind-theme-regular
#
# Drops Munlik's rEFInd theme (https://github.com/bobafetthotmail/refind-theme-regular)
# into the NixOS-managed rEFInd install via boot.loader.refind.additionalFiles.
# The theme ships an os_nixos.png in every icon size, and rEFInd auto-matches
# icons by the first word of each menuentry title — the refind installer
# generates entries titled "NixOS ...", so no per-entry icon directive is
# needed.
{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.services.refind-theme-regular;

  sizeMap = {
    small = {
      big = 128;
      small = 48;
      font = 14;
    };
    medium = {
      big = 256;
      small = 96;
      font = 28;
    };
    large = {
      big = 384;
      small = 144;
      font = 42;
    };
    xlarge = {
      big = 512;
      small = 192;
      font = 42;
    };
  };

  size = sizeMap.${cfg.size};
  sizeDir = "${toString size.big}-${toString size.small}";
  bgSuffix =
    if cfg.variant == "dark"
    then "_dark"
    else "";

  themeSrc = pkgs.fetchFromGitHub {
    owner = "bobafetthotmail";
    repo = "refind-theme-regular";
    rev = "93ff4ef480a42ea0720331723f45c57a7f0bf9c5";
    hash = "sha256-aGaQ1orMDn+4oTntEeIgNrT0vv+BbNztp6anUf4um9Q=";
  };

  # Trim the upstream tree to just the chosen icon size + font, and emit a
  # theme.conf wired to those paths. Mirrors what upstream's install.sh would
  # have built interactively.
  themeDir = pkgs.runCommand "refind-theme-regular" {} ''
    mkdir -p $out/icons $out/fonts
    cp -r ${themeSrc}/icons/${sizeDir} $out/icons/${sizeDir}
    cp ${themeSrc}/fonts/${cfg.font}-${toString size.font}.png $out/fonts/
    cp ${themeSrc}/LICENSE $out/LICENSE
    cat > $out/theme.conf <<EOF
    # Generated by services.refind-theme-regular
    icons_dir themes/refind-theme-regular/icons/${sizeDir}
    big_icon_size ${toString size.big}
    small_icon_size ${toString size.small}
    banner themes/refind-theme-regular/icons/${sizeDir}/bg${bgSuffix}.png
    selection_big themes/refind-theme-regular/icons/${sizeDir}/selection${bgSuffix}-big.png
    selection_small themes/refind-theme-regular/icons/${sizeDir}/selection${bgSuffix}-small.png
    font themes/refind-theme-regular/fonts/${cfg.font}-${toString size.font}.png
    EOF
  '';

  # Walk themeDir and produce { "themes/refind-theme-regular/<relpath>" = <storePath>; }
  # for every file. Reading from the derivation forces a build during eval.
  collectFiles = root: subdir: let
    fullPath =
      if subdir == ""
      then root
      else "${root}/${subdir}";
    entries = builtins.readDir fullPath;
    process = name: type: let
      rel =
        if subdir == ""
        then name
        else "${subdir}/${name}";
    in
      if type == "directory"
      then collectFiles root rel
      else {"themes/refind-theme-regular/${rel}" = "${root}/${rel}";};
  in
    foldl' (acc: name: acc // process name entries.${name}) {} (attrNames entries);
in {
  options.services.refind-theme-regular = {
    enable = mkEnableOption "the refind-theme-regular rEFInd theme";

    size = mkOption {
      type = types.enum ["small" "medium" "large" "xlarge"];
      default = "medium";
      description = ''
        Icon size set. Pixel pairs (big/small): small=128/48,
        medium=256/96, large=384/144, xlarge=512/192. Pick larger sizes
        for high-DPI panels.
      '';
    };

    variant = mkOption {
      type = types.enum ["light" "dark"];
      default = "dark";
      description = "Background and selection color scheme.";
    };

    font = mkOption {
      type = types.enum ["source-code-pro-extralight" "nimbus-mono" "ubuntu-mono"];
      default = "source-code-pro-extralight";
      description = "Bitmap font face used in menus.";
    };
  };

  config = mkIf cfg.enable {
    assertions = [
      {
        assertion = config.boot.loader.refind.enable;
        message = "services.refind-theme-regular requires boot.loader.refind.enable = true.";
      }
    ];

    boot.loader.refind.extraConfig = ''
      include themes/refind-theme-regular/theme.conf
    '';

    boot.loader.refind.additionalFiles = collectFiles themeDir "";
  };
}
