tasks:
  - before: |
      sh <(curl -L https://nixos.org/nix/install) --no-daemon
  - init: |
        [[ ! -z $SSH_PRIVATE_KEY  ]] &&
          echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_ed25519 &&
          chmod 644 ~/.ssh/id_ed25519
        [[ ! -z $SSH_PUBLIC_KEY  ]] &&
          echo $SSH_PUBLIC_KEY | base64 -d > ~/.ssh/id_ed25519.pub &&
          chmod 644 ~/.ssh/id_ed25519.pub