keys:
  # User keys
  - &user_arosenfeld age1zmev49pzr0wxqdw4m5t5pk0ma98dchmxlucl0u6w2ajj762624qq7v3u43

  # Host keys (derived from ssh-ed25519 host keys via ssh-to-age)
  - &host_cloud age1s9hjg4ls5k0wrd3rcsmtrywe6535907368druhpreg5c5lu2sguq2pdq0a
  - &host_storage age1cclv24tdyu7t95utdzmtlp0a6mmku277sjckftlf7ldd8r487d5synct7g
  - &host_raider age1heelrhsk3nv40ct8e4r0l4nt9hrd8a5x692w5z30vvhsgujfcc6q9a7c2m
  - &host_raspi3 age17y8vddr4fjxxx7awm6qamcuckh6etme2fpay7a80gjev0z4xyaeqcstpds
  - &host_r2s age1qgp8m729pgef4pmz9fdje029pmsa9zp46u00ld8g6kzhf2ufs4sqphyy9w
  - &host_router age15masa7pw2dmr456hx2tk0uhx8vjup9dflfjeq6mey7v0335r2qnqjj6e90
  - &host_cottage age16663xfcw6jc4k49yfanpcvapym8phkgy57k5f56wzdyl9ty7vdequu6wm4
  - &host_g14 age1xhex4q8x4z76tspzwq75vlktj5nhcdv8gmm4zgqyq4a02490uuwq6ehdh5
  - &host_octopi age17vmpwxh5uaqke3sxyc4ehj5pun4mr85x9w93s40rg7s4pyaph5xscf9wsa

creation_rules:
  - path_regex: secrets/sops/cloud\.yaml$
    key_groups:
      - age:
          - *user_arosenfeld
          - *host_cloud

  - path_regex: secrets/sops/storage\.yaml$
    key_groups:
      - age:
          - *user_arosenfeld
          - *host_storage

  - path_regex: secrets/sops/raider\.yaml$
    key_groups:
      - age:
          - *user_arosenfeld
          - *host_raider

  - path_regex: secrets/sops/cottage\.yaml$
    key_groups:
      - age:
          - *user_arosenfeld
          - *host_cottage

  - path_regex: secrets/sops/micro\.yaml$
    key_groups:
      - age:
          - *user_arosenfeld

  - path_regex: secrets/sops/common\.yaml$
    key_groups:
      - age:
          - *user_arosenfeld
          - *host_cloud
          - *host_storage
          - *host_raider
          - *host_raspi3
          - *host_r2s
          - *host_router
          - *host_cottage
          - *host_g14
          - *host_octopi
