{
  imports = [
    ./cloudflared.nix
    ./vault.nix
    ./yarr.nix
    ./blog.nix
    ./finance-tracker.nix
    ./gatus.nix
    ./ntfy.nix
    ./planka.nix
    ./plausible.nix
    ./ask.nix
    ./radicle.nix
    ./search.nix
    ./siyuan.nix
    ./sillytavern.nix
    ./webui.nix
  ];
}
