# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.supportedFilesystems = ["zfs"];
  #boot.initrd.mdadmConf = "ARRAY /dev/md/md2  metadata=1.2 UUID=124fee3e:a0556cd6:665bdc85:8630511b name=md2";

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0eae046a-b904-4da3-a177-d324f02bd60c";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/52B7-5238";
    fsType = "vfat";
  };
  fileSystems."/boot-2" = {
    device = "/dev/disk/by-uuid/52DC-9C20";
    fsType = "vfat";
  };
  fileSystems."/boot-3" = {
    device = "/dev/disk/by-uuid/5302-3514";
    fsType = "vfat";
  };
  fileSystems."/boot-4" = {
    device = "/dev/disk/by-uuid/5327-75C8";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/6a05db72-4868-44fe-af57-160f3742fb78";}
    {device = "/dev/disk/by-uuid/1c40195a-842e-42ec-b0fc-92c6a2843ece";}
    {device = "/dev/disk/by-uuid/d000bef0-b552-4f86-a13a-d3aa64daf3bf";}
    {device = "/dev/disk/by-uuid/9dbc8088-64ae-4ba6-bb5d-1ca4a593fb5e";}
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
