# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "mpt3sas" "nvme" "usbhid" "uas" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel" "it87"];
  boot.extraModulePackages = with config.boot.kernelPackages; [it87];
  boot.kernelParams = ["acpi_osi=\"Windows 2015\""];

  fileSystems."/mnt/data" = {
    depends = ["/mnt/storage"];
    device = "/mnt/storage";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home" = {
    depends = ["/mnt/storage"];
    device = "/mnt/storage/homes";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/mnt/storage" = {
    fsType = "btrfs";
    device = "/dev/disk/by-uuid/0ab1aa6e-aa33-4825-b7f9-10f9487d8713";
    options = ["nofail" "compress=zstd"];
  };

  systemd.services.docker.after = ["mnt-storage.mount"];
  systemd.services.docker.requires = ["mnt-storage.mount"];

  networking.useDHCP = false;
  networking.useNetworkd = true;
  networking.bridges = {
    "br0" = {
      interfaces = ["enp3s0"];
    };
  };
  networking.interfaces.br0.useDHCP = true;

  powerManagement.powertop.enable = true;

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
