# Zola configuration for arsfeld.dev blog

base_url = "https://blog.arsfeld.dev"
title = "Alex Rosenfeld"
description = "Technical blog about NixOS configurations, self-hosting, and infrastructure automation"
author = "Alex Rosenfeld"

# Language and locale
default_language = "en"
compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml"]

# Theme configuration
theme = "custom"

# Build settings
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "dracula"
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[extra]
# Theme settings
home_subtitle = "NixOS configurations, self-hosting guides, and infrastructure patterns"

# Analytics - Self-hosted Plausible
enable_plausible = true
plausible_domain = "arsfeld.dev"
plausible_api = "https://plausible.arsfeld.dev"

# Social links
social_links = [
    { name = "GitHub", url = "https://github.com/arsfeld" },
    { name = "Twitter", url = "https://twitter.com/alexrosenfeld10" },
    { name = "Email", url = "mailto:alex@rosenfeld.one" }
]

# Theme customization
color_scheme = "auto"
accent_color = "#0066cc"
show_reading_time = true
show_table_of_contents = true
enable_related_posts = true

# Featured projects for homepage
featured_projects = [
    { name = "NixOS Config", description = "Personal NixOS configuration for multiple machines", url = "https://github.com/arsfeld/nixos" },
    { name = "Self-Hosting Guide", description = "Comprehensive guide to self-hosting with NixOS", url = "/posts/self-hosting-nixos" }
]

# Taxonomies
[[taxonomies]]
name = "tags"
feed = true