{
  imports = [
    ./ai.nix
    ./ask.nix
    ./auth.nix
    ./backrest-portal.nix
    ./backrest-public-vhosts.nix
    ./beszel.nix
    ./bitmagnet.nix
    ./cinephage.nix
    ./cloud-sync.nix
    ./cloudflared.nix
    ./db.nix
    ./develop.nix
    ./eufy.nix
    ./files.nix
    ./forgejo-runner.nix
    ./glance.nix
    ./home-apps.nix
    ./home-assistant.nix
    ./home.nix
    ./immich-pixel-sync
    ./immich.nix
    ./infra.nix
    ./isponsorblock.nix
    ./linkding.nix
    ./marinara.nix
    ./media-apps.nix
    ./media-automation.nix
    ./media-streaming.nix
    ./media.nix
    ./misc.nix
    ./network-tools.nix
    ./ntfy.nix
    ./opencloud.nix
    ./pia.nix
    ./qbittorrent-vpn.nix
    ./tablet-sync.nix
    ./transmission-vpn.nix
    ./nfs.nix
    ./samba.nix
    ./search.nix
    ./seafile.nix
    ./stashfin.nix
    ./vault.nix
    ./vpn-exit-nodes.nix
    ./yarr.nix
  ];
}
