{
  imports = [
    ./ai.nix
    ./ask.nix
    ./auth.nix
    ./backrest-portal.nix
    ./backrest-public-vhosts.nix
    ./beszel.nix
    ./bitmagnet.nix
    ./cinephage.nix
    ./cloud-sync.nix
    ./cloudflared.nix
    ./db.nix
    ./develop.nix
    ./files.nix
    ./forgejo-runner.nix
    ./glance.nix
    ./home.nix
    ./immich.nix
    ./infra.nix
    ./isponsorblock.nix
    ./linkding.nix
    ./media.nix
    ./misc.nix
    ./morphic.nix
    ./ntfy.nix
    ./qbittorrent-vpn.nix
    ./rqbit.nix
    ./transmission-vpn.nix
    ./nfs.nix
    ./samba.nix
    ./search.nix
    ./seafile.nix
    ./stashfin.nix
    ./vault.nix
    ./yarr.nix
  ];
}
