# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = ["amdgpu"]; # Early KMS for AMD iGPU
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  # Hybrid GPU configuration
  # - AMD Renoir (Vega iGPU) at PCI 04:00.0 for daily use / power efficiency
  # - NVIDIA GTX 1660 Ti Mobile at PCI 01:00.0 for gaming / compute
  services.xserver.videoDrivers = ["nvidia"];

  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = true; # Enable D3 power management
    # Deliberately off. finegrained sets NVreg_DynamicPowerManagement=0x02,
    # but this GPU reports "Runtime D3 status: Not supported" and the platform
    # reports "S0ix Power Management: Not Supported", so fine-grained D3 never
    # actually worked here — it bought no idle power saving and is a candidate
    # for the driver parking the memory clock at its 810 MHz idle value.
    powerManagement.finegrained = false;
    # Closed kernel modules, deliberately. The open modules mandate GSP
    # firmware, and on this Turing laptop GPU GSP-RM owns clock/power
    # management and gets it wrong: the dGPU sat in P5 with the memory clock
    # pinned at its 810 MHz idle value while Forza held it at 100% util, and
    # reported "Runtime D3 status: Not supported" despite finegrained above.
    # GSP also ignores the NVreg_RegistryDwords PowerMizer keys set in
    # configuration.nix, which is why that block previously did nothing.
    # Closed modules are what let NVreg_EnableGpuFirmware=0 turn GSP off.
    open = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;

    prime = {
      offload = {
        enable = true;
        enableOffloadCmd = true; # Provides nvidia-offload command
      };
      amdgpuBusId = "PCI:4:0:0";
      nvidiaBusId = "PCI:1:0:0";
    };
  };

  # Hardware acceleration
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  security.protectKernelImage = false;

  boot.kernelParams = ["mem_sleep_default=deep"];

  boot.resumeDevice = "/dev/disk/by-partlabel/disk-main-swap";

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
