# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = ["amdgpu"]; # Early KMS for AMD iGPU
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  # Hybrid GPU configuration
  # - AMD Renoir (Vega iGPU) at PCI 04:00.0 for daily use / power efficiency
  # - NVIDIA GTX 1660 Ti Mobile at PCI 01:00.0 for gaming / compute
  services.xserver.videoDrivers = ["nvidia"];

  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = true;

    # dGPU boot-time power clamp. Lifted at boot by
    # systemd.services.nvidia-unclamp-tgp in configuration.nix -- but read that
    # unit's KNOWN LIMITATION note before trusting it: the 60 W it establishes
    # has been seen reverting to 30 W partway through a play session, and the
    # trigger is not yet identified.
    #
    # This comment previously called the state below a hardware ceiling and said
    # to tune expectations rather than settings. That was wrong, and the tell was
    # always available: the same machine ran Forza Horizon 5 at 40-60 fps on high
    # under Windows while Linux managed ~30 on medium/low. Same silicon, same
    # VBIOS, so it was never a hardware limit.
    #
    # The state it described is real, but it is the *clamped* state, not a
    # ceiling: memory pinned at 810 MHz against a 6001 MHz spec, an enforced
    # 30 W limit against the board's own 60 W default, clpeak at 26.2 GB/s of a
    # ~288 GB/s bus. After the module reload, on the same hardware: 60 W,
    # 6001 MHz, P0, 243 GB/s. Core clock looked "healthy" at ~1800 MHz only
    # because perf level 1 already permits 2100, which is what made this read
    # as a memory-specific hardware fault rather than a power clamp.
    #
    # One methodology note, since it cost real time: several numbers in the
    # original block were idle telemetry. At true idle this GPU reads 405 MHz
    # memory and PCIe Gen 1; the "Gen 2 x8" figure is what a lightly loaded or
    # clamped GPU reports, and max link width actually reads 16x. Sample under a
    # sustained load and check whether SW Power Cap is Active before concluding
    # anything about a clock.
    #
    # Ruled out by measurement. Do not re-attempt:
    #   - NVreg_RegistryDwords PowerMizer keys (PowerMizerEnable,
    #     PowerMizerLevel, PerfLevelSrc). Dropped from the driver around 530,
    #     so dead on 595 with GSP both on and off. An earlier revision of this
    #     config carried them under a comment asserting they fixed the P5 lock.
    #     They never did — the assertion was never measured.
    #   - open = false plus NVreg_EnableGpuFirmware=0 to disable GSP:
    #     26.23 GB/s, memory clock still 810 MHz.
    #   - NVreg_DynamicPowerManagement=0x00 on top of that: 26.26 GB/s,
    #     memory clock still 810 MHz. The config as it stands measures 26.25.
    #     Three driver configurations, one number.
    #   - nvidia-smi -pl / -lmc / -ac: all refused. NVIDIA blocks power-limit
    #     and memory-clock control on consumer mobile parts. -lgc is accepted
    #     but the core clock was never the constraint.
    #   - Dropping pcie_aspm=force (see boot.kernelParams in configuration.nix).
    #     ASPM already reads Disabled on both link ends; still Gen 2.
    #
    # Untested leads, both needing hardware: a display on the dGPU's own output
    # (card0-DP-1, the USB-C DisplayPort — HDMI is wired to the iGPU), which
    # would make it a display GPU rather than a pure offload target; and an
    # ASUS BIOS update.
    #
    # finegrained would set NVreg_DynamicPowerManagement=0x02, but the driver
    # reports "Runtime D3 status: Not supported" and the platform reports
    # "S0ix Power Management: Not Supported", so it only ever claimed a
    # capability this machine does not have. Off, to keep the config honest.
    powerManagement.finegrained = false;

    # Open modules: CachyOS pre-builds and packages proprietary nvidia modules for 610.x.
    # Set open = false to use the prebuilt CachyOS nvidia driver.
    open = false;
    nvidiaSettings = true;
    package = pkgs.nvidia_cachyos-bore;

    prime = {
      offload = {
        enable = true;
        enableOffloadCmd = true; # Provides nvidia-offload command
      };
      amdgpuBusId = "PCI:4:0:0";
      nvidiaBusId = "PCI:1:0:0";
    };
  };

  # Hardware acceleration
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  security.protectKernelImage = false;

  boot.kernelParams = ["mem_sleep_default=deep"];

  boot.resumeDevice = "/dev/disk/by-partlabel/disk-main-swap";

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
