name: "Test"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Install devbox
      uses: jetpack-io/devbox-install-action@v0.2.0
      with:
        enable-cache: true

    - name: Build Linux
      if: runner.os == 'Linux'
      run: devbox shell -- colmena build --on storage,micro